import { defineCollection, z } from 'astro:content';

/**
 * Publications collection — every paper is a single JSON file under
 * src/content/publications/. Schema mirrors spec §6.1.
 *
 * Authors are stored as an ordered array; `myAuthorIndex` flags which
 * one is me so PaperItem can render the bold + underlined version.
 */
const publications = defineCollection({
  type: 'data',
  schema: z.object({
    id: z.string(),
    title: z.string(),
    authors: z.array(z.string()).min(1),
    myAuthorIndex: z.number().int().min(0),
    year: z.number().int(),
    venue: z.string(),
    venueFull: z.string(),
    type: z.enum(['conference', 'journal', 'arxiv', 'under-review', 'workshop']),
    status: z.enum(['published', 'to-appear', 'under-review']),
    abstract: z.string().optional(),
    pdfUrl: z.string().url().optional(),
    arxivId: z.string().optional(),
    doi: z.string().optional(),
    codeUrl: z.string().url().optional(),
    slidesUrl: z.string().url().optional(),
    videoUrl: z.string().url().optional(),
    topics: z.array(z.string()).default([]),
    bibtex: z.string(),
    awards: z.array(z.string()).default([]),
    citations: z.number().int().nonnegative().optional(),
    /** Optional override for the citation key used in the BibTeX entry. */
    citationKey: z.string().optional(),
    /** IDs of related papers (e.g. arXiv preprint ↔ conference version). */
    relatedPaperIds: z.array(z.string()).default([]),
  }),
});

/**
 * Projects collection — MDX deep-dives under src/content/projects/.
 * Frontmatter carries the metadata; the MDX body is the long-form
 * write-up, mounted on /projects/[slug]/.
 */
const projects = defineCollection({
  type: 'content',
  schema: z.object({
    title: z.string(),
    summary: z.string(),
    /** One-line tagline used on cards and the page header. */
    tagline: z.string(),
    venue: z.string().optional(),
    year: z.number().int().optional(),
    status: z.enum(['published', 'to-appear', 'under-review', 'ongoing']).default('published'),
    topics: z.array(z.string()).default([]),
    paperId: z.string().optional(),
    paperUrl: z.string().url().optional(),
    codeUrl: z.string().url().optional(),
    awards: z.array(z.string()).default([]),
    /** Display order on the /projects index. Lower = earlier. */
    order: z.number().int().default(99),
    /** True for ongoing/no-public-paper projects (e.g. work at Arm). */
    ongoing: z.boolean().default(false),
    draft: z.boolean().default(false),
  }),
});

/**
 * News collection — short MDX entries under src/content/news/.
 * Each entry is one news item; reverse-chronological by `date`.
 * MDX body is optional; the headline + brief usually suffice.
 */
const news = defineCollection({
  type: 'content',
  schema: z.object({
    title: z.string(),
    date: z.coerce.date(),
    /** True for entries where the exact day isn't known — page hides it. */
    approximateDate: z.boolean().default(false),
    /** Optional link the headline links to. Internal paths or full URLs both OK. */
    href: z.string().refine(
      (s) => s.startsWith('/') || /^https?:\/\//.test(s) || s.startsWith('mailto:'),
      'href must be an internal path (/...) or a full URL',
    ).optional(),
    tags: z.array(z.string()).default([]),
    draft: z.boolean().default(false),
  }),
});

/**
 * Blog collection — MDX posts under src/content/blog/.
 *
 * `status` drives the lifecycle:
 *   idea       → /blog/ideas/<slug>      noindex,  excluded from /blog/, RSS, sitemap
 *   draft      → /blog/drafts/<slug>     noindex,  excluded from /blog/, RSS, sitemap
 *   published  → /blog/<slug>            indexed,  included in /blog/, RSS, sitemap
 *   archived   → /blog/<slug>            indexed,  included in sitemap, hidden from /blog/
 *
 * Series frontmatter carries the multi-part metadata for posts that
 * belong to a sequence (renders Part N of M cards + prev/next).
 */
const blog = defineCollection({
  type: 'content',
  schema: z.object({
    title: z.string(),
    description: z.string(),
    date: z.coerce.date(),
    updated: z.coerce.date().optional(),
    tags: z.array(z.string()).default([]),
    /** Lifecycle state. Default 'draft' so a new file is private until promoted. */
    status: z.enum(['idea', 'draft', 'published', 'archived']).default('draft'),
    /** Multi-part series. The slug is derived from the post; `name` is the display title. */
    series: z
      .object({
        name: z.string(),
        slug: z.string(),
        part: z.number().int().min(1),
        total: z.number().int().min(1),
      })
      .optional(),
    /** Set false to suppress the auto-rendered table of contents. */
    toc: z.boolean().default(true),
    /**
     * Audio narration controls (Phase 8.2).
     *
     * `audio: 'enabled'` is the default — every published post gets a
     * narration MP3 generated by OpenAI tts-1-hd, stored on R2.
     * `audio: 'disabled'` skips generation for posts where TTS would
     * sound bad (heavy math, dense code).
     *
     * `audioVoice` overrides the default voice. Default is `echo`.
     *
     * `audioReadAs` is the safety valve — set it to a hand-written
     * narration script and the preprocessor returns it verbatim.
     * Use this for posts whose auto-preprocessed body sounds awkward.
     */
    audio: z.enum(['enabled', 'disabled']).default('enabled'),
    audioVoice: z
      .enum(['alloy', 'echo', 'fable', 'onyx', 'nova', 'shimmer'])
      .default('echo'),
    audioReadAs: z.string().optional(),
    /**
     * Citation rendering style. `numeric` (default) numbers citations
     * in order of first appearance per post. `author-year` is reserved
     * for a future PR — schema-accepted but not yet wired into the
     * remark plugin; falls back to numeric.
     */
    citationStyle: z.enum(['numeric', 'author-year']).default('numeric'),
    /**
     * Per-post bibliography. The key (e.g. `smith2023`) is what
     * `<Cite key="...">` references. Only entries actually cited in
     * the body get rendered in `<ReferencesList />`; unused entries
     * are logged as build warnings and dropped from the output.
     */
    references: z
      .record(
        z.string(),
        z.object({
          authors: z.array(z.string()).default([]),
          title: z.string().optional(),
          venue: z.string().optional(),
          year: z.number().int().optional(),
          url: z.string().url().optional(),
          doi: z.string().optional(),
          arxivId: z.string().optional(),
          pages: z.string().optional(),
        }),
      )
      .optional(),
  }),
});

/**
 * Photos collection — MDX entries under src/content/photos/, one per
 * photo. Image source files live alongside under src/content/photos/img/.
 * Privacy: GPS is never stored in the sidecar JSON or rendered; the
 * frontmatter `location` field is free-text only.
 */
const photos = defineCollection({
  type: 'content',
  schema: ({ image }) => z.object({
    title: z.string(),
    date: z.coerce.date(),
    /** Optional free-text location. Don't put GPS or precise addresses. */
    location: z.string().optional(),
    /** Optional caption (markdown supported in body). */
    caption: z.string().optional(),
    tags: z.array(z.string()).default([]),
    /** Relative path to the source image — Astro's image() helper. */
    image: image(),
    /** Optional grouping; the /photos UI shows an album filter when set. */
    album: z.string().optional(),
    /** Larger 2×2 cell in the grid. */
    featured: z.boolean().default(false),
    /** Set false to hide without deleting (also hidden in the lightbox). */
    visible: z.boolean().default(true),
    /**
     * Layout mode for the cell:
     *   - cover  (default): fill cell, crop overflow
     *   - contain: fit whole image inside cell with paper-bg padding
     *   - tall: 1×2 cell for portrait orientation
     * If unset, the page picks `contain` for ~1 in 5 photos
     * deterministically (stable hash of slug) for visual rhythm.
     */
    displayMode: z.enum(['cover', 'contain', 'tall']).optional(),
  }),
});

/**
 * Press / Mentions collection — short MDX entries under
 * src/content/press/, one per article / podcast / interview /
 * thesis-acknowledgment / blog-mention.
 *
 * Reverse-chronological list at /press. Body MDX is optional and
 * unused by the index page; reserved for future per-entry pages if
 * we ever want them.
 */
const press = defineCollection({
  type: 'content',
  schema: z.object({
    title: z.string(),
    date: z.coerce.date(),
    outlet: z.string(),
    /** Public URL to the source article / episode / page. */
    url: z.string().url(),
    /** Optional pull-quote or short summary. */
    excerpt: z.string().optional(),
    type: z
      .enum(['article', 'podcast', 'interview', 'thesis-acknowledgment', 'blog-mention'])
      .default('article'),
    draft: z.boolean().default(false),
  }),
});

/**
 * Talks deep-dive collection — optional MDX page per talk at
 * /talks/<slug>/. The /talks index page also links to a deep-dive
 * when a matching slug exists in this collection.
 *
 * Embeds:
 *   - youtubeId: 11-char YouTube video id (NOT the full URL)
 *   - driveFileId: Google Drive file id (NOT the full URL)
 *   - slidesUrl: PDF or Drive link, embedded inline via <iframe>
 */
const talks = defineCollection({
  type: 'content',
  schema: z.object({
    title: z.string(),
    date: z.coerce.date(),
    venue: z.string(),
    venueFull: z.string(),
    location: z.string(),
    /** Type of talk — drives the small "invited" badge on the index. */
    type: z.enum(['conference', 'invited']).default('conference'),
    awards: z.array(z.string()).default([]),
    /** YouTube video id (e.g. "VAsB1XBuRZ0" — not the full URL). */
    youtubeId: z.string().optional(),
    /** Google Drive file id (e.g. "1zM1oa..." — not the full URL). */
    driveFileId: z.string().optional(),
    /** URL to slides PDF — Drive or self-hosted under /public/slides/. */
    slidesUrl: z.string().url().optional(),
    /** Optional id matching publications.id for cross-linking. */
    paperId: z.string().optional(),
    draft: z.boolean().default(false),
  }),
});

export const collections = {
  publications,
  projects,
  news,
  blog,
  photos,
  press,
  talks,
};

